image: ruby:2.7

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby
        
before_script:
  - bundle install --path=vendor

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
