# Site Settings
lang: fr
title: Hub Makerspace
tagline: Fablab Makerspace
email: adrien.bracq@unilasalle.fr
description: >
  Hub Makerspace Unilasalle Amiens
baseurl: ""
imgurl : "/img"
editurl : "https://gitlab.com/makerspace-unilasalle/campus-amiens/hub-amiens/-/edit/master"

url: "https://makerspace-amiens.fr"
permalink: pretty
favicon: favicon.png
#gh_sponsor: chrisrhymes
hide_share_buttons: true
theme_color: '#eeeeee'

fixed_navbar: top

paginate: 100
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: 

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-tagories
  - jekyll-spaceship
  - jekyll-pdf-embed
  - jekyll-remote-include

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - archives/


livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Makerspace Amiens"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true
      

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
  projects: 
    output: true
    layout: project
    image: https://via.placeholder.com/800x600
    show_sidebar: false
  sensors: 
    output: true
    layout: component
    image: https://via.placeholder.com/800x600
    show_sidebar: false
  actuators: 
    output: true
    layout: component
    image: https://via.placeholder.com/800x600
    show_sidebar: false
  tutorials: 
    output: true
    layout: tutorial
    image: https://via.placeholder.com/800x600
    show_sidebar: false


# Where things are
jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    config:
      tex:
        inlineMath:
          - ['$','$']
          - ['\(','\)']
        displayMath:
          - ['$$','$$']
          - ['\[','\]']
      svg:
        fontCache: 'global'
    optimize: # optimization on building stage to check and add mathjax scripts
      enabled: true # value `false` for adding to all pages
      include: []   # include patterns for math expressions checking (regexp)
      exclude: []   # exclude patterns for math expressions checking (regexp)
  plantuml-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: 'plantuml!'
      custom: ['@startuml', '@enduml']
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/
